site_name: My Docs
site_url: https://inventare.github.io/django-image-uploader-widget
repo_url: https://github.com/inventare/django-image-uploader-widget
repo_name: inventare/django-image-uploader-widget

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins:
  - glightbox
