name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        django-version: ['3.2', '4.0', '4.1', '4.2']
        exclude:
          - python-version: '3.7'
            django-version: '4.0'
          - python-version: '3.7'
            django-version: '4.1'
          - python-version: '3.7'
            django-version: '4.2'

    services:
      selenium:
        image: selenium/standalone-chrome
      
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium
        pip install django==${{ matrix.django-version }}
        
    - name: Prepare Selenium
      # https://github.com/marketplace/actions/setup-chromedriver
      uses: nanasess/setup-chromedriver@master

    - name: Launch Browser
      run: |
        google-chrome --version
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode

    - name: Run Tests
      run: python manage.py test
      env:
        DATABASE_USE_POSTGRES: 1
        POSTGRES_PORT: 5432
        POSTGRES_HOST: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: postgres
