name: Test Widget Features

on: pull_request

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - run: yarn

    - run: yarn test
      env:
        CI: true
